### ISSUE TITLE
PID

### ISSUE THREAD

**Issue by carl1961** [Apehaenger/Another-HotPlate-Firmware#3]
I have the 200mmx200mm Hot plate running, I did 2 PID runs, I am unclear what range of PID log do we get out PID settings from PID  Site.
this is first check box selected

Proportional Gain
652.9891699724827
[-]
Integral Time
49.12152279269201
[sec]
Derivative Time
4.391186049870651
[sec]
Integral Gain
13.293341347097455
[-]
Derivative Gain
2867.3969338997817
[-]

![first_PID](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/a77243ac-37c5-4ba8-b653-238a464c47f2)

Files and pictures uploaded to Github
https://grabcad.com/library/customized-upgraded-946c-electronic-hot-plate-1
![IMG_20230516_181325246_HDR](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/d53af094-d198-482a-90a4-08633eadd137)

**Comment by Apehaenger** [comment]
Hi Carl!

I also had trouble to understand at first.

You've to transfer the three 'Gain' values to the hotplate settings... **but** your "Derivative Gain" look pretty high. Might be that they're right, as it highly depends on you systems (heater + thermocouple) characteristics, but you probably also made the same failure as I did at first.
Did you checked this quite good PDF? https://github.com/pidtuner/pidtuner.github.io/blob/master/assets/doc/PID%20Tuner.pdf
In special since I made it like shown in page 15, I got quite better results.

Also, PID-Tune only the relevant temp range. For me it was the temp range between 100-160°C.

BTW: Looks quite good how you integrated the OLED into the case... and also feels good to see my FW within your project :-)

**Comment by carl1961** [comment]
Thanks for fast reply 
selecting rang 100 - 160C  I get this, I'll go read the PDF and educate myself.

PID Gains
Proportional Gain
-102.66156124855367
[-]
Integral Time
799.3790483152761
[sec]
Derivative Time
0
[sec]
Integral Gain
-0.1284266349798848
[-]
Derivative Gain
0
[-]


getting the 200x200mm hot plate was for some big clock parts

![IMG_20230517_103135745_HDR](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/0ced7116-e5e9-402e-927b-7466f86d2c0d)

I already built a bigger one from a old tee shirt press, but was so slow heating, but it was not a waste because I heat violin wood on it before gluing, give you more assembly time when using hide glue.
![IMG_20230517_103113936_HDR](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/df453f95-10eb-4ba0-a849-5dd6f65f5dca)
![IMG_20230517_103049974_HDR](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/70dc4ec8-6636-442e-878b-73e49e6dea2a)
