### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by carl1961** [Apehaenger/Another-HotPlate-Firmware#4]
I did my first reflows and Hotplate works fine. 
I wound up setting me up a dummy 3dprinter with Arduino mega and a ramps 1.5 and I used the PID autotune to find my PID's only wired attached to my hotplate was to the SSR to tune the heat on and off. the K sensor from Arduino setup I just placed in center of plate. I did not remove the cover off sensor. ( can explain why I used un-modified K prob if you need the know)
https://marlinfw.org/docs/gcode/M303.html Marlin firmware defaults to 5 cycles, but numer of cycles can be any amount. It took over 30 minutes to tune.

P: 85.6 
I:  2.6
D: 690.4 
I get over shoot like maybe 9 degrees , so I think it should be ok.

My question is what the number's mean in your profile's , because when any profiles run I see they start at 40C  and I see no 40.
Thanks for you work, 

profile Sn42Bi576Ag04 was to cold for my solder paste Sn63Pb37 

![s-l1600](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/4e472bf4-9bd2-4739-8e64-ed3254a44d7f)

profile Sn965Ag30Cu05 was too hot, but I used it.

I am just a copy cat coder!  I managed to get me a profile added to your program (right or wrong) it seems to work.
![Screenshot 2023-05-25 060617](https://github.com/Apehaenger/Another-HotPlate-Firmware/assets/3056821/766aebb4-6f79-4c3e-8164-f5d84a7d2ee4)

have you seen this code? he has autotune  
https://learn.adafruit.com/sous-vide-powered-by-arduino-the-sous-viduino/autotune

Sn63Pb37 data sheet

[tds-4860p.pdf](https://github.com/Apehaenger/Another-HotPlate-Firmware/files/11566030/tds-4860p.pdf)

**Comment by Apehaenger** [comment]
Hi Carl!

> I did my first reflows and Hotplate works fine.

Quite cool and nice to hear!!


> I wound up setting me up a dummy 3dprinter with Arduino mega and a ramps 1.5 and I used the PID autotune to find my PID's only wired attached to my hotplate was to the SSR to tune the heat on and off. the K sensor from Arduino setup I just placed in center of plate. I did not remove the cover off sensor. ( can explain why I used un-modified K prob if you need the know)
> https://marlinfw.org/docs/gcode/M303.html Marlin firmware defaults to 5 cycles, but numer of cycles can be any amount. It took over 30 minutes to tune.

Cool idea!! However, that's what I tried to save one with the implementation of [PID Tuner](https://pidtuner.com/), but I also already recognized that it's complicated as well ;-)


> P: 85.6
> I: 2.6
> D: 690.4

Look pretty high for me, and as far as I remember, I don't use derivative PID setting. Will check some older communication later and probably post you a link of it. Might be probably also helpful to you ;-)
  
> I get over shoot like maybe 9 degrees , so I think it should be ok.

Yes! 9°C is pretty good. IIRC I set my bangOff to 5 degrees as my K delay is rather high.


> My question is what the number's mean in your profile's , because when any profiles run I see they start at 40C and I see no 40.
> Thanks for you work,

Indeed, there's no 40 within the profile(s). When I start a profile, it start with the current temp and then it switches to the next profile temp. target. Let me explain with one profile:

```
typedef struct
    {
        uint16_t time_s; // After n seconds...
        uint16_t temp_c; // reach this target temp
    } ProfileTimeTarget;

    typedef struct
    {
        uint8_t length; // length of (the next) timeTargets[]
        ProfileTimeTarget *timeTargets;
        uint16_t duration_s; // Duration (s) of the complete profile (last entry)
    } ProfileTimeTargets;
    ...
    const ProfileTimeTargets _profileTimeTarget_tSn965Ag30Cu05 = {4, (ProfileTimeTarget[]){{90, 150}, {180, 175}, {210, 217}, {240, 249}}, 240};
```

ProfileTimeTarget and ProfileTimeTargets are somehow static and also redundant, mainly because I haven't been clever enough that time :-/

The first number of `_profileTimeTarget_tSn965Ag30Cu05` is the size of the following `ProfileTimeTarget` array. So the 4 here means, the next ( `ProfileTimeTarget` array) parameter has to have 4 element.
Each of these `ProfileTimeTarget` elements has two values: time_s and temp_c. Thus: `{{90, 150}, {180, 175}, {210, 217}, {240, 249}}`means:
After 90 seconds, temp target = 150°C,
after 180 seconds, temp target = 175°C, and so fort.
The last `_profileTimeTarget_tSn965Ag30Cu05` parameter is the overall profile temp. Normally the same value as the last time target entry.


> I managed to get me a profile added to your program (right or wrong) it seems to work.

Look okay to me! Well done ;-)



> have you seen this code? he has autotune

Yes. Planned to integrate his [Arduino-PID-AutoTune-Library](https://github.com/br3ttb/Arduino-PID-AutoTune-Library) but never found good results, why I dropped it again. It's also rather old, even if it doesn't mean anything bad.

> Sn63Pb37 data sheet

Quite thanks, will integrate it on the next rainy days ;-) ... if you've more profiles/solder-paste-types you're interested in, feel free to post them ;-)

**Comment by carl1961** [comment]
I may made mistake then..
"( ProfileTimeTarget array) parameter has to have 4 element"
I changed the original 3 to a 4  , I was thinking it was related to the number of menu items

**Comment by carl1961** [comment]
well what I did to make profile actually did not work when running,  it added to the menu but when I did a actual real run it was not right. I had to remove all that and just changed temp on your profile.
